name: Unit Tests

# Controls when the action will run.
on: [push, pull_request]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tests:
    name: Run unittests
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: python src/test.py

  linter:
      name: Indentation Linter
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint
          # pip install -r requirements.txt
      - name: Lint with pylint
        run: |
          python -m pylint --disable=all -e W0311 --jobs=0 --indent-string='  ' **/*.py
