name: Code Checks

# Controls when the action will run.
on: [push, pull_request]

jobs:
  tests:
    name: Run UnitTests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: python -m unittest test.test

  linter:
    name: Indentation Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint
          # pip install -r requirements.txt
      - name: Lint with pylint
        run: |
          python -m pylint --disable=all -e W0311 --jobs=0 --indent-string='    ' **/*.py

  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: --recursive --in-place --aggressive --max-line-length=180 .
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: autopep8 action fixes
          title: Fixes by autopep8 action
          body: This is an auto-generated PR with fixes by autopep8.
          labels: autopep8, automated pr
          reviewers: timmermansjoy
          branch: autopep8-patches
